// Generated by CoffeeScript 1.6.3
(function() {
  this.Controls = (function() {
    function Controls(_opts) {
      this.options = _opts;
      this.setupEventListeners();
    }

    Controls.prototype.app = function() {
      return this.options.app;
    };

    Controls.prototype.bind = function(scope, fn) {
      return function() {
        return fn.apply(scope, arguments);
      };
    };

    Controls.prototype.setupEventListeners = function() {
      document.addEventListener('mousedown', this.bind(this, this.mousedown), false);
      return document.addEventListener('keydown', this.bind(this, this.keydown), false);
    };

    Controls.prototype.mousedown = function(event) {
      event.preventDefault();
      event.stopPropagation();
      console.log("Mousedown");
      return this.app().createDisturbance();
    };

    Controls.prototype.keydown = function(event) {
      console.log("Keydown (event.which = " + event.which + ")");
      if (event.which === 49) {
        this.app().createDisturbance(GridDisturbance);
      }
      if (event.which === 50) {
        this.app().createDisturbance(VerticalDisturbance);
      }
      if (event.which === 51) {
        this.app().createDisturbance(BumpDisturbance);
      }
      if (event.which === 27) {
        console.log('[ESC] clearing disturbances array');
        this.app().disturbances = [];
        return this.app().grid.reset();
      }
    };

    return Controls;

  })();

}).call(this);
