// Generated by CoffeeScript 1.6.3
(function() {
  this.Controls = (function() {
    function Controls(_opts) {
      this.options = _opts;
      this.setupEventListeners();
    }

    Controls.prototype.app = function() {
      return this.options.app;
    };

    Controls.prototype.bind = function(scope, fn) {
      return function() {
        return fn.apply(scope, arguments);
      };
    };

    Controls.prototype.setupEventListeners = function() {
      return document.addEventListener('mousedown', this.bind(this, this.mousedown), false);
    };

    Controls.prototype.mousedown = function(event) {
      event.preventDefault();
      event.stopPropagation();
      return this.app().createDisturbance();
    };

    return Controls;

  })();

}).call(this);
