// Generated by CoffeeScript 1.6.3
(function() {
  this.GridDisturbance = (function() {
    function GridDisturbance(_opts) {
      this.options = _opts;
    }

    GridDisturbance.prototype.stepCount = function() {
      return this._stepCount || (this._stepCount = 0);
    };

    GridDisturbance.prototype.step = function() {
      var box, i, _i, _len, _ref;
      _ref = this.options.grid.boxes();
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        box = _ref[i];
        box.rotation.x += 0.001 * (i + 1);
      }
      return this._stepCount = this.stepCount() + 1;
    };

    GridDisturbance.prototype.done = function() {
      var val;
      val = Math.abs(((0.001 * this.stepCount()) % THREE.Math.PI2) - THREE.Math.PI2);
      console.log(val);
      if (this.stepCount() > 0 && val < 0.001) {
        return true;
      }
      return false;
    };

    return GridDisturbance;

  })();

}).call(this);
